AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: PhotoAlbum Lambdas
Resources:
  SearchLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: photo-search
      Handler: LF2.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambdas/LF2
      Description: "Searching Lambda"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::197953848710:role/service-role/LF2-role-dg7sdzil"
      Environment:
        Variables:
          REGION: us-east-1
  UploadLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: photo-index
      Handler: LF1.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambdas/LF1
      Description: "Indexing Lambda"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::197953848710:role/service-role/LF1-role-01l9kubi"
      Environment:
        Variables:
          REGION: us-east-1