AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: PhotoAlbum Lambdas
Resources:
  SearchLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: photo-search
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambdas
      Description: "Searching Lambda"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::197953848710:role/service-role/codebuild-LambdaPipeline-service-role"
      Environment:
        Variables:
          REGION: us-east-1
  UploadLambda:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: photo-index
      Handler: LF1.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambdas
      Description: "Indexing Lambda"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::197953848710:role/service-role/codebuild-LambdaPipeline-service-role"
      Environment:
        Variables:
          REGION: us-east-1